from compiler import *

####################################################################################################################
#  Each map icon record contains the following fields:
#  1) Map icon id: used for referencing map icons in other files.
#     The prefix icon_ is automatically added before each map icon id.
#  2) Map icon flags. See header_map icons.py for a list of available flags
#  3) Mesh name.
#  4) Scale. 
#  5) Sound.
#  6) Offset x position for the flag icon.
#  7) Offset y position for the flag icon.
#  8) Offset z position for the flag icon.
####################################################################################################################

banner_scale = 0.3
avatar_scale = 0.15

map_icons = [
  ("player",0,"lav_infantry_medium", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0),
  ("player_horseman",0,"lav_horseman_heraldic", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("gray_knight",0,"knight_a", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("vaegir_knight",0,"knight_b", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("flagbearer_a",0,"flagbearer_a", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("flagbearer_b",0,"flagbearer_b", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("peasant",0,"peasant_a", avatar_scale,snd.footstep_grass, 0.15, 0.173, 0),
  ("khergit",0,"khergit_horseman", avatar_scale,snd.gallop, 0.15, 0.173, 0),
  ("khergit_horseman_b",0,"khergit_horseman_b", avatar_scale,snd.gallop, 0.15, 0.173, 0),
  ("axeman",0,"bandit_a", avatar_scale,snd.footstep_grass, 0.15, 0.173, 0),
  ("woman",0,"woman_a", avatar_scale,snd.footstep_grass, 0.15, 0.173, 0),
  ("woman_b",0,"woman_b", avatar_scale,snd.footstep_grass, 0.15, 0.173, 0),
  ("town",mcn_no_shadow,"map_town_a", 0.35,0),
  ("town_steppe",mcn_no_shadow,"map_town_steppe_a", 0.35,0),
  ("town_desert",mcn_no_shadow,"map_town_desert_a", 0.35,0),
  ("village_a",mcn_no_shadow,"map_village_a", 0.45, 0),
  ("village_b",mcn_no_shadow,"map_village_b", 0.45, 0),
  ("village_c",mcn_no_shadow,"map_village_c", 0.45, 0),
  ("village_burnt_a",mcn_no_shadow,"map_village_burnt_a", 0.45, 0),
  ("village_deserted_a",mcn_no_shadow,"map_village_deserted_a", 0.45, 0),
  ("village_burnt_b",mcn_no_shadow,"map_village_burnt_b", 0.45, 0),
  ("village_deserted_b",mcn_no_shadow,"map_village_deserted_b", 0.45, 0),
  ("village_burnt_c",mcn_no_shadow,"map_village_burnt_c", 0.45, 0),
  ("village_deserted_c",mcn_no_shadow,"map_village_deserted_c", 0.45, 0),
  ("village_snow_a",mcn_no_shadow,"map_village_snow_a", 0.45, 0),
  ("village_snow_burnt_a",mcn_no_shadow,"map_village_snow_burnt_a", 0.45, 0),
  ("village_snow_deserted_a",mcn_no_shadow,"map_village_snow_deserted_a", 0.45, 0),


  ("camp",mcn_no_shadow,"camp_tent", 0.13, 0),
  ("ship",mcn_no_shadow,"boat_sail_on", 0.23, snd.footstep_grass, 0.0, 0.05, 0),
  ("ship_on_land",mcn_no_shadow,"boat_sail_off", 0.23, 0),

  ("castle_a",mcn_no_shadow,"map_castle_a", 0.35,0),
  ("castle_b",mcn_no_shadow,"map_castle_b", 0.35,0),
  ("castle_c",mcn_no_shadow,"map_castle_c", 0.35,0),
  ("castle_d",mcn_no_shadow,"map_castle_d", 0.35,0),
  ("town_snow",mcn_no_shadow,"map_town_snow_a", 0.35,0),


  ("castle_snow_a",mcn_no_shadow,"map_castle_snow_a", 0.35,0),
  ("castle_snow_b",mcn_no_shadow,"map_castle_snow_b", 0.35,0),
  ("mule",0,"icon_mule", 0.2,snd.footstep_grass, 0.15, 0.173, 0),
  ("cattle",0,"icon_cow", 0.2,snd.footstep_grass, 0.15, 0.173, 0),
  ("training_ground",mcn_no_shadow,"training", 0.35,0),

  ("bridge_a",mcn_no_shadow,"map_river_bridge_a", 1.27,0),
  ("bridge_b",mcn_no_shadow,"map_river_bridge_b", 0.7,0),
  ("bridge_snow_a",mcn_no_shadow,"map_river_bridge_snow_a", 1.27,0),

  ("bandit_lair",mcn_no_shadow,"map_bandit_lair", 0.45, 0),

  # NEW ICONS


  ("player_female",     0, "lav_infantry_female", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  #("player_marshall",   0, "dedal_map_swadia_lord_c", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  #("player_lord",       0, "dedal_map_swadia_lord_a", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("swadia_king",       0, "dedal_map_swadia_king_a", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  #("swadia_marshall",   0, "dedal_map_swadia_lord_c", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("swadia_lord",       0, "dedal_map_swadia_lord_a", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("vaegir_king",       0, "dedal_map_vaegir_king_a", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  #("vaegir_marshall",   0, "dedal_map_vaegir_lord_c", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("vaegir_lord",       0, "dedal_map_vaegir_lord_a", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("khergit_king",      0, "dedal_map_khergit_king_a", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  #("khergit_marshall",  0, "dedal_map_khergit_lord_c", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("khergit_lord",      0, "dedal_map_khergit_lord_a", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("nordic_king",       0, "dedal_map_nordic_king_b", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0),
  #("nordic_marshall",   0, "dedal_map_nordic_lord_c", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0),
  ("nordic_lord",       0, "dedal_map_nordic_lord_b", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0),
  ("rhodok_king",       0, "dedal_map_rhodok_king_a", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  #("rhodok_marshall",   0, "dedal_map_rhodok_lord_c", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("rhodok_lord",       0, "dedal_map_rhodok_lord_a", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("sarranid_king",     0, "somebody_map_sarranid_king_a", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  #("sarranid_marshall", 0, "dedal_map_sarranid_lord_c", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("sarranid_lord",     0, "somebody_map_sarranid_lord_a", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  #("dknight_king",      0, "dedal_map_swadia_king_a", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  #("dknight_marshall",  0, "dedal_map_swadia_lord_c", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("dknight_lord",      0, "lav_horseman_heavy", avatar_scale, snd.gallop, 0.15, 0.173, 0),

  ("swadia_patrol",   0, "dedal_map_swadia_band_a", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0),
  ("swadia_scouts",   0, "dedal_map_swadia_crossbowman", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0),
  ("swadia_elites",   0, "dedal_map_swadia_lancer", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("swadia_rebels",   0, "dedal_map_swadia_king_c", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("vaegir_patrol",   0, "dedal_map_vaegir_guard", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0),
  ("vaegir_scouts",   0, "dedal_map_forest_bandit", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0),
  ("vaegir_elites",   0, "dedal_map_vaegir_archer", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("vaegir_rebels",   0, "dedal_map_vaegir_king_c", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("khergit_patrol",   0, "dedal_map_khergit_warrior", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("khergit_scouts",   0, "dedal_map_khergit_archer", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("khergit_elites1",  0, "dedal_map_khergit_band_a", avatar_scale, snd.gallop, 0.15, 0.173, 0), # Red Horde
  ("khergit_elites2",  0, "dedal_map_khergit_band_b", avatar_scale, snd.gallop, 0.15, 0.173, 0), # Blue Horde
  ("khergit_rebels",   0, "dedal_map_khergit_king_c", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("nordic_patrol",   0, "dedal_map_nordic_band_a", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0),
  ("nordic_scouts",   0, "dedal_map_nordic_archer", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0),
  ("nordic_elites",   0, "dedal_map_nordic_warrior", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0), # Berserkers
  ("nordic_rebels",   0, "dedal_map_nordic_king_c", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0),
  ("rhodok_patrol",   0, "dedal_map_rhodok_band_a", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0),
  ("rhodok_scouts",   0, "dedal_map_rhodok_crossbowman", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0),
  ("rhodok_elites",   0, "knight_b", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("rhodok_rebels",   0, "dedal_map_rhodok_king_c", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("sarranid_patrol",   0, "somebody_map_sarranid_guard", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0),
  ("sarranid_scouts",   0, "somebody_map_sarranid_archer", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0),
  ("sarranid_elites",   0, "lav_horseman_sarranid", avatar_scale, snd.gallop, 0.15, 0.173, 0), # Jihadists
  ("sarranid_rebels",   0, "somebody_map_sarranid_king_c", avatar_scale, snd.gallop, 0.15, 0.173, 0),

  ("outlaw_mercenaries", 0, "lav_infantry_heavy", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("outlaw_sea_raiders", 0, "dedal_map_sea_raider", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0),
  ("outlaw_archer_bandits", 0, "dedal_map_ranger", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0),
  ("outlaw_desert_bandits", 0, "lav_horseman_khergit", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("outlaw_mountain_bandits", 0, "dedal_map_mountain_bandit", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("outlaw_deserters", 0, "lav_horseman_medium", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0),

  ("manhunters", 0, "dedal_map_manhunter", avatar_scale, snd.gallop, 0.15, 0.173, 0),
  ("lone_man", 0, "player", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0),
  ("quest_caravan", 0, "lav_caravan_guild", avatar_scale, snd.footstep_grass, 0.15, 0.173, 0),

  ("custom_banner_01",0,"custom_map_banner_01", banner_scale, 0,
   [
     (ti_on_init_map_icon,
      [
        (store_trigger_param_1, ":party_no"),
        (party_get_slot, ":leader_troop", ":party_no", slot_town_lord),
        (try_begin),
          (ge, ":leader_troop", 0),
          (cur_map_icon_set_tableau_material, "tableau_custom_banner_square", ":leader_troop"),
        (try_end),
        ]),
     ]),
  ("custom_banner_02",0,"custom_map_banner_02", banner_scale, 0,
   [
     (ti_on_init_map_icon,
      [
        (store_trigger_param_1, ":party_no"),
        (party_get_slot, ":leader_troop", ":party_no", slot_town_lord),
        (try_begin),
          (ge, ":leader_troop", 0),
          (cur_map_icon_set_tableau_material, "tableau_custom_banner_short", ":leader_troop"),
        (try_end),
        ]),
     ]),
  ("custom_banner_03",0,"custom_map_banner_03", banner_scale, 0,
   [
     (ti_on_init_map_icon,
      [
        (store_trigger_param_1, ":party_no"),
        (party_get_slot, ":leader_troop", ":party_no", slot_town_lord),
        (try_begin),
          (ge, ":leader_troop", 0),
          (cur_map_icon_set_tableau_material, "tableau_custom_banner_tall", ":leader_troop"),
        (try_end),
        ]),
     ]),

  # Banners

  ("banner_a01",  0, "ymbsp_map_flag_a01", banner_scale, 0),
  ("banner_a02",  0, "ymbsp_map_flag_a02", banner_scale, 0),
  ("banner_a03",  0, "ymbsp_map_flag_a03", banner_scale, 0),
  ("banner_a04",  0, "ymbsp_map_flag_a04", banner_scale, 0),
  ("banner_a05",  0, "ymbsp_map_flag_a05", banner_scale, 0),
  ("banner_a06",  0, "ymbsp_map_flag_a06", banner_scale, 0),
  ("banner_a07",  0, "ymbsp_map_flag_a07", banner_scale, 0),
  ("banner_a08",  0, "ymbsp_map_flag_a08", banner_scale, 0),
  ("banner_a09",  0, "ymbsp_map_flag_a09", banner_scale, 0),
  ("banner_a10",  0, "ymbsp_map_flag_a10", banner_scale, 0),
  ("banner_a11",  0, "ymbsp_map_flag_a11", banner_scale, 0),
  ("banner_a12",  0, "ymbsp_map_flag_a12", banner_scale, 0),
  ("banner_a13",  0, "ymbsp_map_flag_a13", banner_scale, 0),
  ("banner_a14",  0, "ymbsp_map_flag_a14", banner_scale, 0),
  ("banner_a15",  0, "ymbsp_map_flag_a15", banner_scale, 0),
  ("banner_a16",  0, "ymbsp_map_flag_a16", banner_scale, 0),
  ("banner_a17",  0, "ymbsp_map_flag_a17", banner_scale, 0),
  ("banner_a18",  0, "ymbsp_map_flag_a18", banner_scale, 0),
  ("banner_a19",  0, "ymbsp_map_flag_a19", banner_scale, 0),
  ("banner_a20",  0, "ymbsp_map_flag_a20", banner_scale, 0),
  ("banner_a21",  0, "ymbsp_map_flag_a21", banner_scale, 0),
  ("banner_b01",  0, "ymbsp_map_flag_b01", banner_scale, 0),
  ("banner_b02",  0, "ymbsp_map_flag_b02", banner_scale, 0),
  ("banner_b03",  0, "ymbsp_map_flag_b03", banner_scale, 0),
  ("banner_b04",  0, "ymbsp_map_flag_b04", banner_scale, 0),
  ("banner_b05",  0, "ymbsp_map_flag_b05", banner_scale, 0),
  ("banner_b06",  0, "ymbsp_map_flag_b06", banner_scale, 0),
  ("banner_b07",  0, "ymbsp_map_flag_b07", banner_scale, 0),
  ("banner_b08",  0, "ymbsp_map_flag_b08", banner_scale, 0),
  ("banner_b09",  0, "ymbsp_map_flag_b09", banner_scale, 0),
  ("banner_b10",  0, "ymbsp_map_flag_b10", banner_scale, 0),
  ("banner_b11",  0, "ymbsp_map_flag_b11", banner_scale, 0),
  ("banner_b12",  0, "ymbsp_map_flag_b12", banner_scale, 0),
  ("banner_b13",  0, "ymbsp_map_flag_b13", banner_scale, 0),
  ("banner_b14",  0, "ymbsp_map_flag_b14", banner_scale, 0),
  ("banner_b15",  0, "ymbsp_map_flag_b15", banner_scale, 0),
  ("banner_b16",  0, "ymbsp_map_flag_b16", banner_scale, 0),
  ("banner_b17",  0, "ymbsp_map_flag_b17", banner_scale, 0),
  ("banner_b18",  0, "ymbsp_map_flag_b18", banner_scale, 0),
  ("banner_b19",  0, "ymbsp_map_flag_b19", banner_scale, 0),
  ("banner_b20",  0, "ymbsp_map_flag_b20", banner_scale, 0),
  ("banner_b21",  0, "ymbsp_map_flag_b21", banner_scale, 0),
  ("banner_c01",  0, "ymbsp_map_flag_c01", banner_scale, 0),
  ("banner_c02",  0, "ymbsp_map_flag_c02", banner_scale, 0),
  ("banner_c03",  0, "ymbsp_map_flag_c03", banner_scale, 0),
  ("banner_c04",  0, "ymbsp_map_flag_c04", banner_scale, 0),
  ("banner_c05",  0, "ymbsp_map_flag_c05", banner_scale, 0),
  ("banner_c06",  0, "ymbsp_map_flag_c06", banner_scale, 0),
  ("banner_c07",  0, "ymbsp_map_flag_c07", banner_scale, 0),
  ("banner_c08",  0, "ymbsp_map_flag_c08", banner_scale, 0),
  ("banner_c09",  0, "ymbsp_map_flag_c09", banner_scale, 0),
  ("banner_c10",  0, "ymbsp_map_flag_c10", banner_scale, 0),
  ("banner_c11",  0, "ymbsp_map_flag_c11", banner_scale, 0),
  ("banner_c12",  0, "ymbsp_map_flag_c12", banner_scale, 0),
  ("banner_c13",  0, "ymbsp_map_flag_c13", banner_scale, 0),
  ("banner_c14",  0, "ymbsp_map_flag_c14", banner_scale, 0),
  ("banner_c15",  0, "ymbsp_map_flag_c15", banner_scale, 0),
  ("banner_c16",  0, "ymbsp_map_flag_c16", banner_scale, 0),
  ("banner_c17",  0, "ymbsp_map_flag_c17", banner_scale, 0),
  ("banner_c18",  0, "ymbsp_map_flag_c18", banner_scale, 0),
  ("banner_c19",  0, "ymbsp_map_flag_c19", banner_scale, 0),
  ("banner_c20",  0, "ymbsp_map_flag_c20", banner_scale, 0),
  ("banner_c21",  0, "ymbsp_map_flag_c21", banner_scale, 0),
  ("banner_d01",  0, "ymbsp_map_flag_d01", banner_scale, 0),
  ("banner_d02",  0, "ymbsp_map_flag_d02", banner_scale, 0),
  ("banner_d03",  0, "ymbsp_map_flag_d03", banner_scale, 0),
  ("banner_d04",  0, "ymbsp_map_flag_d04", banner_scale, 0),
  ("banner_d05",  0, "ymbsp_map_flag_d05", banner_scale, 0),
  ("banner_d06",  0, "ymbsp_map_flag_d06", banner_scale, 0),
  ("banner_d07",  0, "ymbsp_map_flag_d07", banner_scale, 0),
  ("banner_d08",  0, "ymbsp_map_flag_d08", banner_scale, 0),
  ("banner_d09",  0, "ymbsp_map_flag_d09", banner_scale, 0),
  ("banner_d10",  0, "ymbsp_map_flag_d10", banner_scale, 0),
  ("banner_d11",  0, "ymbsp_map_flag_d11", banner_scale, 0),
  ("banner_d12",  0, "ymbsp_map_flag_d12", banner_scale, 0),
  ("banner_d13",  0, "ymbsp_map_flag_d13", banner_scale, 0),
  ("banner_d14",  0, "ymbsp_map_flag_d14", banner_scale, 0),
  ("banner_d15",  0, "ymbsp_map_flag_d15", banner_scale, 0),
  ("banner_d16",  0, "ymbsp_map_flag_d16", banner_scale, 0),
  ("banner_d17",  0, "ymbsp_map_flag_d17", banner_scale, 0),
  ("banner_d18",  0, "ymbsp_map_flag_d18", banner_scale, 0),
  ("banner_d19",  0, "ymbsp_map_flag_d19", banner_scale, 0),
  ("banner_d20",  0, "ymbsp_map_flag_d20", banner_scale, 0),
  ("banner_d21",  0, "ymbsp_map_flag_d21", banner_scale, 0),
  ("banner_e01",  0, "ymbsp_map_flag_e01", banner_scale, 0),
  ("banner_e02",  0, "ymbsp_map_flag_e02", banner_scale, 0),
  ("banner_e03",  0, "ymbsp_map_flag_e03", banner_scale, 0),
  ("banner_e04",  0, "ymbsp_map_flag_e04", banner_scale, 0),
  ("banner_e05",  0, "ymbsp_map_flag_e05", banner_scale, 0),
  ("banner_e06",  0, "ymbsp_map_flag_e06", banner_scale, 0),
  ("banner_e07",  0, "ymbsp_map_flag_e07", banner_scale, 0),
  ("banner_e08",  0, "ymbsp_map_flag_e08", banner_scale, 0),
  ("banner_e09",  0, "ymbsp_map_flag_e09", banner_scale, 0),
  ("banner_e10",  0, "ymbsp_map_flag_e10", banner_scale, 0),
  ("banner_e11",  0, "ymbsp_map_flag_e11", banner_scale, 0),
  ("banner_e12",  0, "ymbsp_map_flag_e12", banner_scale, 0),
  ("banner_e13",  0, "ymbsp_map_flag_e13", banner_scale, 0),
  ("banner_e14",  0, "ymbsp_map_flag_e14", banner_scale, 0),
  ("banner_e15",  0, "ymbsp_map_flag_e15", banner_scale, 0),
  ("banner_e16",  0, "ymbsp_map_flag_e16", banner_scale, 0),
  ("banner_e17",  0, "ymbsp_map_flag_e17", banner_scale, 0),
  ("banner_e18",  0, "ymbsp_map_flag_e18", banner_scale, 0),
  ("banner_e19",  0, "ymbsp_map_flag_e19", banner_scale, 0),
  ("banner_e20",  0, "ymbsp_map_flag_e20", banner_scale, 0),
  ("banner_e21",  0, "ymbsp_map_flag_e21", banner_scale, 0),
  ("banner_f01",  0, "ymbsp_map_flag_f01", banner_scale, 0),
  ("banner_f02",  0, "ymbsp_map_flag_f02", banner_scale, 0),
  ("banner_f03",  0, "ymbsp_map_flag_f03", banner_scale, 0),
  ("banner_f04",  0, "ymbsp_map_flag_f04", banner_scale, 0),
  ("banner_f05",  0, "ymbsp_map_flag_f05", banner_scale, 0),
  ("banner_f06",  0, "ymbsp_map_flag_f06", banner_scale, 0),
  ("banner_f07",  0, "ymbsp_map_flag_f07", banner_scale, 0),
  ("banner_f08",  0, "ymbsp_map_flag_f08", banner_scale, 0),
  ("banner_f09",  0, "ymbsp_map_flag_f09", banner_scale, 0),
  ("banner_f10",  0, "ymbsp_map_flag_f10", banner_scale, 0),
  ("banner_f11",  0, "ymbsp_map_flag_f11", banner_scale, 0),
  ("banner_f12",  0, "ymbsp_map_flag_f12", banner_scale, 0),
  ("banner_f13",  0, "ymbsp_map_flag_f13", banner_scale, 0),
  ("banner_f14",  0, "ymbsp_map_flag_f14", banner_scale, 0),
  ("banner_f15",  0, "ymbsp_map_flag_f15", banner_scale, 0),
  ("banner_f16",  0, "ymbsp_map_flag_f16", banner_scale, 0),
  ("banner_f17",  0, "ymbsp_map_flag_f17", banner_scale, 0),
  ("banner_f18",  0, "ymbsp_map_flag_f18", banner_scale, 0),
  ("banner_f19",  0, "ymbsp_map_flag_f19", banner_scale, 0),
  ("banner_f20",  0, "ymbsp_map_flag_f20", banner_scale, 0),
  ("banner_f21",  0, "ymbsp_map_flag_f21", banner_scale, 0),
  ("banner_g01",  0, "ymbsp_map_flag_g01", banner_scale, 0),
  ("banner_g02",  0, "ymbsp_map_flag_g02", banner_scale, 0),
  ("banner_g03",  0, "ymbsp_map_flag_g03", banner_scale, 0),
  ("banner_g04",  0, "ymbsp_map_flag_g04", banner_scale, 0),
  ("banner_g05",  0, "ymbsp_map_flag_g05", banner_scale, 0),
  ("banner_g06",  0, "ymbsp_map_flag_g06", banner_scale, 0),
  ("banner_g07",  0, "ymbsp_map_flag_g07", banner_scale, 0),
  ("banner_g08",  0, "ymbsp_map_flag_g08", banner_scale, 0),
  ("banner_g09",  0, "ymbsp_map_flag_g09", banner_scale, 0),
  ("banner_g10",  0, "ymbsp_map_flag_g10", banner_scale, 0),
  ("banner_g11",  0, "ymbsp_map_flag_g11", banner_scale, 0),
  ("banner_g12",  0, "ymbsp_map_flag_g12", banner_scale, 0),
  ("banner_g13",  0, "ymbsp_map_flag_g13", banner_scale, 0),
  ("banner_g14",  0, "ymbsp_map_flag_g14", banner_scale, 0),
  ("banner_g15",  0, "ymbsp_map_flag_g15", banner_scale, 0),
  ("banner_g16",  0, "ymbsp_map_flag_g16", banner_scale, 0),
  ("banner_g17",  0, "ymbsp_map_flag_g17", banner_scale, 0),
  ("banner_g18",  0, "ymbsp_map_flag_g18", banner_scale, 0),
  ("banner_g19",  0, "ymbsp_map_flag_g19", banner_scale, 0),
  ("banner_g20",  0, "ymbsp_map_flag_g20", banner_scale, 0),
  ("banner_g21",  0, "ymbsp_map_flag_g21", banner_scale, 0),

  ("banner_default_a", 0, "ymbsp_map_flag_default_a", banner_scale, 0), # Defaults
  ("banner_default_b", 0, "ymbsp_map_flag_default_b", banner_scale, 0),
  ("banner_default_c", 0, "ymbsp_map_flag_default_c", banner_scale, 0),
  ("banner_default_d", 0, "ymbsp_map_flag_default_d", banner_scale, 0),
  ("banner_default_e", 0, "ymbsp_map_flag_default_e", banner_scale, 0),
  
  ("map_flag_kingdom_a", 0, "ymbsp_map_flag_kingdom_a", banner_scale, 0), # Kingdoms
  ("map_flag_kingdom_b", 0, "ymbsp_map_flag_kingdom_b", banner_scale, 0),
  ("map_flag_kingdom_c", 0, "ymbsp_map_flag_kingdom_c", banner_scale, 0),
  ("map_flag_kingdom_d", 0, "ymbsp_map_flag_kingdom_d", banner_scale, 0),
  ("map_flag_kingdom_e", 0, "ymbsp_map_flag_kingdom_e", banner_scale, 0),
  ("map_flag_kingdom_f", 0, "ymbsp_map_flag_kingdom_f", banner_scale, 0),
  ("map_flag_kingdom_g", 0, "ymbsp_map_flag_kingdom_g", banner_scale, 0),

  ("banner_end_marker", 0, "ymbsp_map_flag_default_e", banner_scale, 0),

]
