from compiler import *
register_plugin()

items = [

	["book_atr_a", "Ancient Tract", [("book_c", 0)], itp_type_book|itp_merchandise, 0, 5000, weight(3)|abundance(100), imodbits_none],
	["book_atr_b", "Ancient Tract", [("book_c", 0)], itp_type_book|itp_merchandise, 0, 5000, weight(3)|abundance(100), imodbits_none],

	["book_skl_a", "Biographical Works", [("book_a", 0)], itp_type_book|itp_merchandise, 0, 4000, weight(2)|abundance(100), imodbits_none],
	["book_skl_b", "Biographical Works", [("book_a", 0)], itp_type_book|itp_merchandise, 0, 4000, weight(2)|abundance(100), imodbits_none],
	["book_skl_c", "Biographical Works", [("book_a", 0)], itp_type_book|itp_merchandise, 0, 4000, weight(2)|abundance(100), imodbits_none],
	["book_skl_d", "Biographical Works", [("book_a", 0)], itp_type_book|itp_merchandise, 0, 4000, weight(2)|abundance(100), imodbits_none],
	["book_skl_e", "Biographical Works", [("book_a", 0)], itp_type_book|itp_merchandise, 0, 4000, weight(2)|abundance(100), imodbits_none],
	["book_skl_f", "Biographical Works", [("book_a", 0)], itp_type_book|itp_merchandise, 0, 4000, weight(2)|abundance(100), imodbits_none],
	["book_skl_g", "Biographical Works", [("book_a", 0)], itp_type_book|itp_merchandise, 0, 4000, weight(2)|abundance(100), imodbits_none],
	["book_skl_h", "Biographical Works", [("book_a", 0)], itp_type_book|itp_merchandise, 0, 4000, weight(2)|abundance(100), imodbits_none],
	["book_skl_i", "Biographical Works", [("book_a", 0)], itp_type_book|itp_merchandise, 0, 4000, weight(2)|abundance(100), imodbits_none],
	["book_skl_j", "Biographical Works", [("book_a", 0)], itp_type_book|itp_merchandise, 0, 4000, weight(2)|abundance(100), imodbits_none],

	["book_ref_a", "Encyclopaedia", [("book_open", 0)], itp_type_book|itp_merchandise, 0, 5000, weight(2.5)|abundance(100), imodbits_none],
	["book_ref_b", "Encyclopaedia", [("book_open", 0)], itp_type_book|itp_merchandise, 0, 5000, weight(2.5)|abundance(100), imodbits_none],
	["book_ref_c", "Encyclopaedia", [("book_open", 0)], itp_type_book|itp_merchandise, 0, 5000, weight(2.5)|abundance(100), imodbits_none],
	["book_ref_d", "Encyclopaedia", [("book_open", 0)], itp_type_book|itp_merchandise, 0, 5000, weight(2.5)|abundance(100), imodbits_none],
	["book_ref_e", "Encyclopaedia", [("book_open", 0)], itp_type_book|itp_merchandise, 0, 5000, weight(2.5)|abundance(100), imodbits_none],
	["book_ref_f", "Encyclopaedia", [("book_open", 0)], itp_type_book|itp_merchandise, 0, 5000, weight(2.5)|abundance(100), imodbits_none],

	["book_wpn_a", "Warrior Memoirs", [("book_e", 0)], itp_type_book|itp_merchandise, 0, 3500, weight(1.5)|abundance(100), imodbits_none],
	["book_wpn_b", "Warrior Memoirs", [("book_e", 0)], itp_type_book|itp_merchandise, 0, 3500, weight(1.5)|abundance(100), imodbits_none],
	["book_wpn_c", "Warrior Memoirs", [("book_e", 0)], itp_type_book|itp_merchandise, 0, 3500, weight(1.5)|abundance(100), imodbits_none],
	["book_wpn_d", "Warrior Memoirs", [("book_e", 0)], itp_type_book|itp_merchandise, 0, 3500, weight(1.5)|abundance(100), imodbits_none],

	["book_exp_a", "Tome of Knowledge", [("book_d", 0)], itp_type_book|itp_merchandise, 0, 6000, weight(2.5)|abundance(100), imodbits_none],
	["book_exp_b", "Tome of Knowledge", [("book_d", 0)], itp_type_book|itp_merchandise, 0, 6000, weight(2.5)|abundance(100), imodbits_none],
	["book_exp_c", "Tome of Knowledge", [("book_d", 0)], itp_type_book|itp_merchandise, 0, 6000, weight(2.5)|abundance(100), imodbits_none],

	["book_par_a", "Opus Magnus", [("book_a", 0)], itp_type_book|itp_merchandise, 0, 7500, weight(3)|abundance(100), imodbits_none],
	["book_par_b", "Opus Magnus", [("book_a", 0)], itp_type_book|itp_merchandise, 0, 7500, weight(3)|abundance(100), imodbits_none],

	["book_fac_a", "Historical Chronicles", [("book_f", 0)], itp_type_book|itp_merchandise, 0, 3500, weight(2)|abundance(100), imodbits_none],
	["book_fac_b", "Historical Chronicles", [("book_f", 0)], itp_type_book|itp_merchandise, 0, 3500, weight(2)|abundance(100), imodbits_none],
	["book_fac_c", "Historical Chronicles", [("book_f", 0)], itp_type_book|itp_merchandise, 0, 3500, weight(2)|abundance(100), imodbits_none],

	["book_fam_a", "Genealogical Treatise", [("book_f", 0)], itp_type_book|itp_merchandise, 0, 3000, weight(1.5)|abundance(100), imodbits_none],
	["book_fam_b", "Genealogical Treatise", [("book_f", 0)], itp_type_book|itp_merchandise, 0, 3000, weight(1.5)|abundance(100), imodbits_none],
	["book_fam_c", "Genealogical Treatise", [("book_f", 0)], itp_type_book|itp_merchandise, 0, 3000, weight(1.5)|abundance(100), imodbits_none],
	["book_fam_d", "Genealogical Treatise", [("book_f", 0)], itp_type_book|itp_merchandise, 0, 3000, weight(1.5)|abundance(100), imodbits_none],
	["book_fam_e", "Genealogical Treatise", [("book_f", 0)], itp_type_book|itp_merchandise, 0, 3000, weight(1.5)|abundance(100), imodbits_none],
	["book_fam_f", "Genealogical Treatise", [("book_f", 0)], itp_type_book|itp_merchandise, 0, 3000, weight(1.5)|abundance(100), imodbits_none],
	["book_fam_g", "Genealogical Treatise", [("book_f", 0)], itp_type_book|itp_merchandise, 0, 3000, weight(1.5)|abundance(100), imodbits_none],
	["book_fam_h", "Genealogical Treatise", [("book_f", 0)], itp_type_book|itp_merchandise, 0, 3000, weight(1.5)|abundance(100), imodbits_none],

]

strings = [

	("ancient_author_00", "Andronicus"),
	("ancient_author_01", "Antipholus"),
	("ancient_author_02", "Arthur the Black"),
	("ancient_author_03", "Arviragus the Wise"),
	("ancient_author_04", "Bassanio III of Calradia"),
	("ancient_author_05", "Bertram the Golden Voice"),
	("ancient_author_06", "Costard the Illiterate"),
	("ancient_author_07", "Cymbeline of Amartha"),
	("ancient_author_08", "Donalbain"),
	("ancient_author_09", "Egeus the Magnificent"),
	("ancient_author_10", "Eglamour of Tharma"),
	("ancient_author_11", "Escalus"),
	("ancient_author_12", "Fenton the Green Bard"),
	("ancient_author_13", "Fortinbras"),
	("ancient_author_14", "Gremio the Violent"),
	("ancient_author_15", "Holofernes"),
	("ancient_author_16", "Jaques the Slaughterer"),
	("ancient_author_17", "Lysander the Merciful"),
	("ancient_author_18", "Montano the Sneak"),
	("ancient_author_19", "Nathaniel of Durrin"),
	("ancient_author_20", "Nym of Tulga"),
	("ancient_author_21", "Ollus VII of Calradia"),
	("ancient_author_22", "Panthino the Revengeful"),
	("ancient_author_23", "Philostrate"),
	("ancient_author_24", "Araxenes"),
	("ancient_author_25", "Proteus the Farseer"),
	("ancient_author_26", "Ross the Butcher of Fenada"),
	("ancient_author_27", "Sampson the Great"),
	("ancient_author_28", "Solinus the Lover"),
	("ancient_author_29", "Verges the Diplomat"),

	("modern_author_00", "Adrian of Veluca"),
	("modern_author_01", "Bardolph the Faithful"),
	("modern_author_02", "Boyet Hassamin"),
	("modern_author_03", "Caphis of Dhirim"),
	("modern_author_04", "Charles Devalie"),
	("modern_author_05", "Curan the Traveller"),
	("modern_author_06", "Dion de Tassi"),
	("modern_author_07", "Goneril of Almerra"),
	("modern_author_08", "Guiderius the Vicious"),
	("modern_author_09", "Hugh the Senior"),
	("modern_author_10", "Launce of Derchios"),
	("modern_author_11", "Lennox the Honorable"),
	("modern_author_12", "Lodovico the Scribe"),
	("modern_author_13", "Mamillius of Alburq"),
	("modern_author_14", "Osric of Semmer"),
	("modern_author_15", "Peter the Inspired"),
	("modern_author_16", "Reynaldo of Hanum"),
	("modern_author_17", "Seyton the Strong"),
	("modern_author_18", "Thurio the Lonely"),
	("modern_author_19", "Tubal the Brave"),
	("modern_author_20", "Aegeon the Infamous"),
	("modern_author_21", "Cleomenes Steel-Fist"),
	("modern_author_22", "Denniz Obrahim Ogly"),
	("modern_author_23", "Fleance the Sailor"),
	("modern_author_24", "Leontes the Powerful"),
	("modern_author_25", "Marcus Issirian"),
	("modern_author_26", "Oberon the Loud"),
	("modern_author_27", "Siward of Bjarnighm"),
	("modern_author_28", "Timon the Famous"),
	("modern_author_29", "Cloten the Noble"),

	("book_title_atr_0_a", "Calradian Legionnaire Training"),
	("book_title_atr_0_b", "Of the Ancient Athletes, Vol. I"),
	("book_title_atr_0_c", "Champions of Northern Wars"),
	("book_title_atr_1_a", "Of the Ancient Athletes, Vol. II"),
	("book_title_atr_1_b", "."),
	("book_title_atr_1_c", "."),
	("book_title_atr_2_a", "."),
	("book_title_atr_2_b", "."),
	("book_title_atr_2_c", "."),
	("book_title_atr_3_a", "."),
	("book_title_atr_3_b", "."),
	("book_title_atr_3_c", "."),

	("book_title_skl_trd", "."),
	("book_title_skl_ldr", "."),
	("book_title_skl_prm", "."),
	("book_title_skl_r03", "."),
	("book_title_skl_r04", "."),
	("book_title_skl_r05", "."),
	("book_title_skl_r06", "."),
	("book_title_skl_prs", "."),
	("book_title_skl_eng", "."),
	("book_title_skl_aid", "."),
	("book_title_skl_srg", "."),
	("book_title_skl_wnd", "."),
	("book_title_skl_inv", "."),
	("book_title_skl_spt", "."),
	("book_title_skl_ptf", "."),
	("book_title_skl_tac", "."),
	("book_title_skl_trk", "."),
	("book_title_skl_trn", "."),
	("book_title_skl_r18", "."),
	("book_title_skl_r19", "."),
	("book_title_skl_r20", "."),
	("book_title_skl_r21", "."),
	("book_title_skl_loo", "."),
	("book_title_skl_har", "."),
	("book_title_skl_rid", "."),
	("book_title_skl_ath", "."),
	("book_title_skl_shl", "."),
	("book_title_skl_wpm", "."),
	("book_title_skl_r28", "."),
	("book_title_skl_r29", "."),
	("book_title_skl_r30", "."),
	("book_title_skl_r31", "."),
	("book_title_skl_r32", "."),
	("book_title_skl_pdr", "."),
	("book_title_skl_pth", "."),
	("book_title_skl_pst", "."),
	("book_title_skl_irn", "."),

	("book_title_ref_trd", "."),
	("book_title_ref_ldr", "."),
	("book_title_ref_prm", "."),
	("book_title_ref_r03", "."),
	("book_title_ref_r04", "."),
	("book_title_ref_r05", "."),
	("book_title_ref_r06", "."),
	("book_title_ref_prs", "."),
	("book_title_ref_eng", "."),
	("book_title_ref_aid", "."),
	("book_title_ref_srg", "."),
	("book_title_ref_wnd", "."),
	("book_title_ref_inv", "."),
	("book_title_ref_spt", "."),
	("book_title_ref_ptf", "."),
	("book_title_ref_tac", "."),
	("book_title_ref_trk", "."),
	("book_title_ref_trn", "."),

	("book_title_wpn_0_a", "."),
	("book_title_wpn_0_b", "."),
	("book_title_wpn_1_a", "."),
	("book_title_wpn_1_b", "."),
	("book_title_wpn_2_a", "."),
	("book_title_wpn_2_b", "."),
	("book_title_wpn_3_a", "."),
	("book_title_wpn_3_b", "."),
	("book_title_wpn_4_a", "."),
	("book_title_wpn_4_b", "."),
	("book_title_wpn_5_a", "."),
	("book_title_wpn_5_b", "."),

	("book_title_exp_a", "."),
	("book_title_exp_b", "."),
	("book_title_exp_c", "."),
	("book_title_exp_d", "."),
	("book_title_exp_e", "."),
	("book_title_exp_f", "."),
	("book_title_exp_g", "."),
	("book_title_exp_h", "."),

	("book_title_par_ren_a", "."),
	("book_title_par_ren_b", "."),
	("book_title_par_hon_a", "."),
	("book_title_par_hon_b", "."),
	("book_title_par_rtr_a", "."),
	("book_title_par_rtr_b", "."),

	("book_title_fac_a", "."),
	("book_title_fac_b", "."),
	("book_title_fac_c", "."),
	("book_title_fac_d", "."),
	("book_title_fac_e", "."),
	("book_title_fac_f", "."),
	("book_title_fac_g", "."),
	("book_title_fac_h", "."),
	("book_title_fac_i", "."),
	("book_title_fac_j", "."),

	("book_title_fam_a", "."),
	("book_title_fam_b", "."),
	("book_title_fam_c", "."),
	("book_title_fam_d", "."),
	("book_title_fam_e", "."),
	("book_title_fam_f", "."),
	("book_title_fam_g", "."),
	("book_title_fam_h", "."),
	("book_title_fam_i", "."),
	("book_title_fam_j", "."),
	("book_title_fam_k", "."),
	("book_title_fam_l", "."),
	("book_title_fam_m", "."),
	("book_title_fam_n", "."),
	("book_title_fam_o", "."),
	("book_title_fam_p", "."),

]

ancient_authors_begin = s.ancient_author_00
ancient_authors_end   = s.ancient_author_29 + 1
modern_authors_begin = s.modern_author_00
modern_authors_end   = s.modern_author_29 + 1

ancient_authors_count = ancient_authors_end - ancient_authors_begin
modern_authors_count = modern_authors_end - modern_authors_begin
all_authors_count = modern_authors_end - ancient_authors_begin

scripts = [

	("initialize_books", [

		# Initialize attribute-increasing books
		(assign, reg0, 0),
		(assign, reg1, 1),
		(assign, reg2, 2),
		(assign, reg3, 3),
		(shuffle_range, 0, 4),
		(item_set_slot, itm.book_atr_a, slot_item_book_param, reg0),
		(item_set_slot, itm.book_atr_b, slot_item_book_param, reg1),
		(try_for_range, l.book, itm.book_atr_a, itm.book_atr_b + 1),
			(store_random_in_range, l.min_req, 10, 15),
			(assign, l.max_req, l.min_req),
			(val_max, l.max_req, 12), # Optimal req is at least 12
			(store_random_in_range, l.max_req, l.max_req, 19),
			(store_random_in_range, l.author, 0, ancient_authors_count),
			(store_random_in_range, l.title, 0, 3),
			(store_random_in_range, l.readtime, 192, 241), # 192-240 hours
			(val_mul, l.readtime, 1000), # 1/1000th
			(item_set_slot, l.book, slot_item_subtype, sst_item_book_attribute),
			(item_set_slot, l.book, slot_item_book_bonus, 1),
			(item_set_slot, l.book, slot_item_book_min_req, l.min_req),
			(item_set_slot, l.book, slot_item_book_opt_req, l.max_req),
			(item_set_slot, l.book, slot_item_book_readtime, l.readtime),
			(item_set_slot, l.book, slot_item_book_abundance, 100),
			(item_set_slot, l.book, slot_item_book_price, 100),
			(item_set_slot, l.book, slot_item_book_author, l.author),
			(item_set_slot, l.book, slot_item_book_title, l.title),
		(try_end),

		# Initialize skill-increasing books
		(assign, reg0, skl.trade),
		(assign, reg1, skl.leadership),
		(assign, reg2, skl.prisoner_management),
		(assign, reg3, skl.persuasion),
		(assign, reg4, skl.engineer),
		(assign, reg5, skl.first_aid),
		(assign, reg6, skl.surgery),
		(assign, reg7, skl.wound_treatment),
		(assign, reg8, skl.inventory_management),
		(assign, reg9, skl.spotting),
		(assign, reg10, skl.pathfinding),
		(assign, reg11, skl.tactics),
		(assign, reg12, skl.tracking),
		(assign, reg13, skl.trainer),
		(assign, reg14, skl.looting),
		(assign, reg15, skl.horse_archery),
		(assign, reg16, skl.riding),
		(assign, reg17, skl.athletics),
		(assign, reg18, skl.shield),
		(assign, reg19, skl.weapon_master),
		(assign, reg20, skl.power_draw),
		(assign, reg21, skl.power_throw),
		(assign, reg22, skl.power_strike),
		(assign, reg23, skl.ironflesh),
		(shuffle_range, 0, 24),
		(item_set_slot, itm.book_skl_a, slot_item_book_param, reg0),
		(item_set_slot, itm.book_skl_b, slot_item_book_param, reg1),
		(item_set_slot, itm.book_skl_c, slot_item_book_param, reg2),
		(item_set_slot, itm.book_skl_d, slot_item_book_param, reg3),
		(item_set_slot, itm.book_skl_e, slot_item_book_param, reg4),
		(item_set_slot, itm.book_skl_f, slot_item_book_param, reg5),
		(item_set_slot, itm.book_skl_g, slot_item_book_param, reg6),
		(item_set_slot, itm.book_skl_h, slot_item_book_param, reg7),
		(item_set_slot, itm.book_skl_i, slot_item_book_param, reg8),
		(item_set_slot, itm.book_skl_j, slot_item_book_param, reg9),
		(try_for_range, l.book, itm.book_skl_a, itm.book_skl_j + 1),
			(store_random_in_range, l.min_req, 8, 13),
			(assign, l.max_req, l.min_req),
			(val_max, l.max_req, 10), # Optimal req is at least 12
			(store_random_in_range, l.max_req, l.max_req, 17),
			(store_random_in_range, l.author, 0, ancient_authors_count),
			(store_random_in_range, l.readtime, 120, 169), # 192-240 hours
			(val_mul, l.readtime, 1000), # 1/1000th
			(item_set_slot, l.book, slot_item_subtype, sst_item_book_skill),
			(item_set_slot, l.book, slot_item_book_bonus, 1),
			(item_set_slot, l.book, slot_item_book_min_req, l.min_req),
			(item_set_slot, l.book, slot_item_book_opt_req, l.max_req),
			(item_set_slot, l.book, slot_item_book_readtime, l.readtime),
			(item_set_slot, l.book, slot_item_book_abundance, 100),
			(item_set_slot, l.book, slot_item_book_price, 100),
			(item_set_slot, l.book, slot_item_book_author, l.author),
			(item_set_slot, l.book, slot_item_book_title, 0),
		(try_end),

		# Initialize reference books
		(assign, reg0, skl.trade),
		(assign, reg1, skl.leadership),
		(assign, reg2, skl.prisoner_management),
		(assign, reg3, skl.persuasion),
		(assign, reg4, skl.engineer),
		(assign, reg5, skl.first_aid),
		(assign, reg6, skl.surgery),
		(assign, reg7, skl.wound_treatment),
		(assign, reg8, skl.inventory_management),
		(assign, reg9, skl.spotting),
		(assign, reg10, skl.pathfinding),
		(assign, reg11, skl.tactics),
		(assign, reg12, skl.tracking),
		(assign, reg13, skl.trainer),
		(shuffle_range, 0, 14),
		(item_set_slot, itm.book_ref_a, slot_item_book_param, reg0),
		(item_set_slot, itm.book_ref_b, slot_item_book_param, reg1),
		(item_set_slot, itm.book_ref_c, slot_item_book_param, reg2),
		(item_set_slot, itm.book_ref_d, slot_item_book_param, reg3),
		(item_set_slot, itm.book_ref_e, slot_item_book_param, reg4),
		(item_set_slot, itm.book_ref_f, slot_item_book_param, reg5),
		(try_for_range, l.book, itm.book_ref_a, itm.book_ref_f + 1),
			(store_random_in_range, l.min_req, 8, 13),
			(assign, l.max_req, l.min_req),
			(val_max, l.max_req, 10), # Optimal req is at least 12
			(store_random_in_range, l.max_req, l.max_req, 17),
			(store_random_in_range, l.author, 0, all_authors_count),
			(store_random_in_range, l.readtime, 48, 73), # 192-240 hours
			(val_mul, l.readtime, 1000), # 1/1000th
			(item_set_slot, l.book, slot_item_subtype, sst_item_book_reference),
			(item_set_slot, l.book, slot_item_book_bonus, 1),
			(item_set_slot, l.book, slot_item_book_min_req, l.min_req),
			(item_set_slot, l.book, slot_item_book_opt_req, l.max_req),
			(item_set_slot, l.book, slot_item_book_readtime, l.readtime),
			(item_set_slot, l.book, slot_item_book_abundance, 100),
			(item_set_slot, l.book, slot_item_book_price, 100),
			(item_set_slot, l.book, slot_item_book_author, l.author),
			(item_set_slot, l.book, slot_item_book_title, 0),
		(try_end),

		# Initialize proficiency books
		(assign, reg0, wpt_one_handed_weapon),
		(assign, reg1, wpt_two_handed_weapon),
		(assign, reg2, wpt_polearm),
		(assign, reg3, wpt_archery),
		(assign, reg4, wpt_crossbows),
		(assign, reg5, wpt_throwing),
		(shuffle_range, 0, 6),
		(item_set_slot, itm.book_wpn_a, slot_item_book_param, reg0),
		(item_set_slot, itm.book_wpn_b, slot_item_book_param, reg1),
		(item_set_slot, itm.book_wpn_c, slot_item_book_param, reg2),
		(item_set_slot, itm.book_wpn_d, slot_item_book_param, reg3),
		(try_for_range, l.book, itm.book_wpn_a, itm.book_wpn_d + 1),
			(store_random_in_range, l.min_req, 8, 13),
			(assign, l.max_req, l.min_req),
			(val_max, l.max_req, 10), # Optimal req is at least 12
			(store_random_in_range, l.max_req, l.max_req, 15),
			(store_random_in_range, l.author, 0, all_authors_count),
			(store_random_in_range, l.readtime, 96, 145),
			(val_mul, l.readtime, 1000), # 1/1000th
			(store_random_in_range, l.bonus, 10, 31),
			(store_mul, l.price, l.bonus, 5),
			(store_div, l.abundance, 1500, l.bonus), # 50..150
			(store_random_in_range, l.title, 0, 2),
			(item_set_slot, l.book, slot_item_subtype, sst_item_book_proficiency),
			(item_set_slot, l.book, slot_item_book_bonus, l.bonus),
			(item_set_slot, l.book, slot_item_book_min_req, l.min_req),
			(item_set_slot, l.book, slot_item_book_opt_req, l.max_req),
			(item_set_slot, l.book, slot_item_book_readtime, l.readtime),
			(item_set_slot, l.book, slot_item_book_abundance, l.abundance),
			(item_set_slot, l.book, slot_item_book_price, l.price),
			(item_set_slot, l.book, slot_item_book_author, l.author),
			(item_set_slot, l.book, slot_item_book_title, l.title),
		(try_end),

		# Initialize experience books
		(assign, reg0, 0),
		(assign, reg1, 1),
		(assign, reg2, 2),
		(assign, reg3, 3),
		(assign, reg4, 4),
		(assign, reg5, 5),
		(assign, reg6, 6),
		(assign, reg7, 7),
		(shuffle_range, 0, 8),
		(item_set_slot, itm.book_exp_a, slot_item_book_title, reg0),
		(item_set_slot, itm.book_exp_b, slot_item_book_title, reg1),
		(item_set_slot, itm.book_exp_c, slot_item_book_title, reg2),
		(try_for_range, l.book, itm.book_exp_a, itm.book_exp_c + 1),
			(item_set_slot, l.book, slot_item_book_param, 0),
			(store_random_in_range, l.min_req, 7, 11),
			(assign, l.max_req, l.min_req),
			(val_max, l.max_req, 9),
			(store_random_in_range, l.max_req, l.max_req, 13),
			(store_random_in_range, l.author, 0, all_authors_count),
			(store_random_in_range, l.readtime, 96, 193),
			(val_mul, l.readtime, 1000), # 1/1000th
			(store_random_in_range, l.bonus, 5, 21),
			(store_div, l.abundance, 600, l.bonus), # 30..120
			(val_add, l.abundance, 20), # 50..140
			(store_mul, l.price, l.bonus, 4), # 20..80
			(val_add, l.price, 50), # 70..130
			(val_mul, l.bonus, 100), # 500..2000 xp per book
			(item_set_slot, l.book, slot_item_subtype, sst_item_book_experience),
			(item_set_slot, l.book, slot_item_book_bonus, l.bonus),
			(item_set_slot, l.book, slot_item_book_min_req, l.min_req),
			(item_set_slot, l.book, slot_item_book_opt_req, l.max_req),
			(item_set_slot, l.book, slot_item_book_readtime, l.readtime),
			(item_set_slot, l.book, slot_item_book_abundance, l.abundance),
			(item_set_slot, l.book, slot_item_book_price, l.price),
			(item_set_slot, l.book, slot_item_book_author, l.author),
		(try_end),

		# Initialize parameter-increasing books
		(assign, reg0, 0), # Renown       : adds 25 renown
		(assign, reg1, 1), # Honor        : adds 5 honor
		(assign, reg2, 2), # Right to Rule: adds 5 RtR
		(shuffle_range, 0, 3),
		(item_set_slot, itm.book_par_a, slot_item_book_param, reg0),
		(item_set_slot, itm.book_par_b, slot_item_book_param, reg1),
		(try_for_range, l.book, itm.book_par_a, itm.book_par_c + 1),
			(store_random_in_range, l.min_req, 9, 13),
			(assign, l.max_req, l.min_req),
			(val_max, l.max_req, 11),
			(store_random_in_range, l.max_req, l.max_req, 16),
			(store_random_in_range, l.author, 0, modern_authors_count),
			(val_add, l.author, modern_authors_begin - ancient_authors_begin),
			(store_random_in_range, l.readtime, 168, 217),
			(val_mul, l.readtime, 1000), # 1/1000th
			(try_begin),
				(item_slot_eq, l.book, slot_item_book_param, 0),
				(item_set_slot, l.book, slot_item_book_bonus, 25),
			(else_try),
				(item_set_slot, l.book, slot_item_book_bonus, 5),
			(try_end),
			(store_random_in_range, l.title, 0, 2),
			(item_set_slot, l.book, slot_item_subtype, sst_item_book_parameter),
			(item_set_slot, l.book, slot_item_book_min_req, l.min_req),
			(item_set_slot, l.book, slot_item_book_opt_req, l.max_req),
			(item_set_slot, l.book, slot_item_book_readtime, l.readtime),
			(item_set_slot, l.book, slot_item_book_abundance, 100),
			(item_set_slot, l.book, slot_item_book_price, 100),
			(item_set_slot, l.book, slot_item_book_author, l.author),
			(item_set_slot, l.book, slot_item_book_title, l.title),
		(try_end),

	]),


]