from compiler import *
register_plugin()

simple_triggers = [

(0,
  [
    (map_free),
    (this_or_next|key_clicked, key_left),
    (key_clicked, key_right),
    (assign, reg0, 1),
    (try_begin),
      (key_clicked, key_left),
      (assign, reg0, -1),
    (try_end),
    (try_begin),
      (neg|key_is_down, key_left_shift),
      (neg|key_is_down, key_right_shift),
      (val_mul, reg0, 10),
    (try_end),
    (try_begin),
      (this_or_next|key_is_down, key_left_control),
      (key_is_down, key_right_control),
      (val_mul, reg0, 10),
    (try_end),
    (val_add, "$heraldic_x", reg0),
    (assign, reg0, "$heraldic_x"),
    (display_message, "@{!}X = {reg0}", 0xFF0000),
  ],
),
(0,
  [
    (map_free),
    (this_or_next|key_clicked, key_up),
    (key_clicked, key_down),
    (assign, reg0, 1),
    (try_begin),
      (key_clicked, key_down),
      (assign, reg0, -1),
    (try_end),
    (try_begin),
      (neg|key_is_down, key_left_shift),
      (neg|key_is_down, key_right_shift),
      (val_mul, reg0, 10),
    (try_end),
    (try_begin),
      (this_or_next|key_is_down, key_left_control),
      (key_is_down, key_right_control),
      (val_mul, reg0, 10),
    (try_end),
    (val_add, "$heraldic_y", reg0),
    (assign, reg0, "$heraldic_y"),
    (display_message, "@{!}Y = {reg0}", 0xFF0000),
  ],
),
(0,
  [
    (map_free),
    (this_or_next|key_clicked, key_numpad_plus),
    (key_clicked, key_numpad_minus),
    (assign, reg0, 1),
    (try_begin),
      (key_clicked, key_numpad_minus),
      (assign, reg0, -1),
    (try_end),
    (try_begin),
      (neg|key_is_down, key_left_shift),
      (neg|key_is_down, key_right_shift),
      (val_mul, reg0, 10),
    (try_end),
    (try_begin),
      (this_or_next|key_is_down, key_left_control),
      (key_is_down, key_right_control),
      (val_mul, reg0, 10),
    (try_end),
    (val_add, "$heraldic_s", reg0),
    (assign, reg0, "$heraldic_s"),
    (display_message, "@{!}Scale = {reg0}", 0xFF0000),
  ],
),

]
